import { type IconType } from "react-icons";
import {
    SiAndroidstudio,
    SiAndroid,
    SiAppstore,
    SiApple,
    SiDiscord,
    SiDotnet,
    SiDocker,
    SiExpo,
    SiFirebase,
    SiFastify,
    SiGit,
    SiGithubactions,
    SiGoogleplay,
    SiGraphql,
    SiJest,
    SiJavascript,
    SiKotlin,
    SiMixpanel,
    SiNestjs,
    SiNextdotjs,
    SiNodedotjs,
    SiPostman,
    SiPostgresql,
    SiReact,
    SiRedux,
    SiSentry,
    SiSqlite,
    SiSwift,
    SiTailwindcss,
    SiTypescript,
    SiXcode,
    SiFigma,
} from "react-icons/si";
import {
    TbApi,
    TbAtom2,
    TbBrandReactNative,
    TbMessageCircle,
    TbPlugConnected,
    TbSparkles,
    TbTestPipe,
} from "react-icons/tb";
import { VscJson } from "react-icons/vsc";
import {
    BsLightningCharge,
    BsCodeSquare,
    BsBarChart,
    BsRocket,
} from "react-icons/bs";

type SkillInfo = {
    icon: IconType;
    color: string;
};

const skillMap: Record<string, SkillInfo> = {
    "React Native": { icon: TbBrandReactNative, color: "#61DAFB" },
    "New Architecture": { icon: TbAtom2, color: "#61DAFB" },
    TypeScript: { icon: SiTypescript, color: "#3178C6" },
    JavaScript: { icon: SiJavascript, color: "#F7DF1E" },
    Expo: { icon: SiExpo, color: "#FFFFFF" },
    "Expo EAS": { icon: SiExpo, color: "#A3A3A3" },
    React: { icon: SiReact, color: "#61DAFB" },
    Redux: { icon: SiRedux, color: "#764ABC" },
    "Redux Toolkit": { icon: SiRedux, color: "#764ABC" },
    "RTK Query": { icon: SiRedux, color: "#8B5CF6" },
    Zustand: { icon: BsLightningCharge, color: "#F59E0B" },
    "TanStack Query": { icon: VscJson, color: "#FF4154" },
    GraphQL: { icon: SiGraphql, color: "#E10098" },
    REST: { icon: TbApi, color: "#10B981" },
    WebSockets: { icon: TbPlugConnected, color: "#22C55E" },
    Postman: { icon: SiPostman, color: "#FF6C37" },
    TurboModules: { icon: BsCodeSquare, color: "#61DAFB" },
    "Nitro modules": { icon: BsLightningCharge, color: "#8B5CF6" },
    Swift: { icon: SiSwift, color: "#F05138" },
    Kotlin: { icon: SiKotlin, color: "#7F52FF" },
    "C# (basics)": { icon: SiDotnet, color: "#512BD4" },
    Xcode: { icon: SiXcode, color: "#147EFB" },
    "Android Studio": { icon: SiAndroidstudio, color: "#3DDC84" },
    iOS: { icon: SiApple, color: "#FFFFFF" },
    Android: { icon: SiAndroid, color: "#3DDC84" },
    "Node.js": { icon: SiNodedotjs, color: "#5FA04E" },
    Fastify: { icon: SiFastify, color: "#FFFFFF" },
    NestJS: { icon: SiNestjs, color: "#E0234E" },
    PostgreSQL: { icon: SiPostgresql, color: "#336791" },
    SQLite: { icon: SiSqlite, color: "#0F80CC" },
    MSSQL: { icon: SiDotnet, color: "#CC2927" },
    "Discord.js": { icon: SiDiscord, color: "#5865F2" },
    Docker: { icon: SiDocker, color: "#2496ED" },
    "Next.js": { icon: SiNextdotjs, color: "#FFFFFF" },
    Firebase: { icon: SiFirebase, color: "#DD2C00" },
    Sentry: { icon: SiSentry, color: "#FB4226" },
    Segment: { icon: BsBarChart, color: "#52BD94" },
    Mixpanel: { icon: SiMixpanel, color: "#7856FF" },
    "Google Play": { icon: SiGoogleplay, color: "#34A853" },
    "App Store": { icon: SiAppstore, color: "#0D96F6" },
    TestFlight: { icon: BsRocket, color: "#0D96F6" },
    "CI/CD": { icon: SiGithubactions, color: "#2088FF" },
    CodePush: { icon: BsLightningCharge, color: "#F05138" },
    Jest: { icon: SiJest, color: "#C21325" },
    "React Testing Library": { icon: TbTestPipe, color: "#E33332" },
    "React Native Testing Library": { icon: TbTestPipe, color: "#61DAFB" },
    Detox: { icon: BsCodeSquare, color: "#7B68EE" },
    Git: { icon: SiGit, color: "#F05032" },
    Cursor: { icon: TbSparkles, color: "#A855F7" },
    Claude: { icon: TbMessageCircle, color: "#D97706" },
    "GitHub Actions": { icon: SiGithubactions, color: "#2088FF" },
    "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
    Figma: { icon: SiFigma, color: "#F24E1E" },
};

export function getSkillInfo(skill: string): SkillInfo | null {
    return skillMap[skill] ?? null;
}
